openapi: 3.0.0
info:
  title: Ads API
  description: REST API for querying ads
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /ads:
    get:
      summary: Returns a list of ads.
      description: List of all ads
      operationId: getAds
      responses:
        '200':
          description: A JSON array of ads
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ad'
components:
  schemas:
    Ad:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string